---
layout: single
title:  "소프트웨어 개발 및 응용과정 Day13"
categories:
  - 소프트웨어 개발 및 응용과정
---

## 예외처리 - Try/Catch

* Try/Catch는 예외가 발생했을때 바로 즉시 종료되는 현상을 막아준다
  * try 부분에 수행할 코드 작성
  * catch 부분에 예외 발생시 수행할 코드 작성

```
package class01;

import java.util.InputMismatchException;
import java.util.Scanner;

public class Test01 {
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		int a;

		try {// 트라이문에서 예외가 발생한다면
			a = sc.nextInt();
			System.out.println(10/a);

		} catch (InputMismatchException e) {//int가 아닌 다른 타입을 쓸경우
			System.out.println("숫자써요");
		} catch (ArithmeticException e) {//수학적 오류(0으로 나눌순 없다)
			System.out.println("0으로는 못나눠요");
		}
	}
}

```

* 실행 결과

```
일
숫자써요
```

```
0
0으로는 못나눠요
```

* 원하는 예외 클래스를 만들수도 있다

  * 기존의 Exception 클래스를 상속받아서 만든다

    ```
    class MyException extends Exception {//내가 원하는 예외 생성
    	MyException(String message) {
    		//특정문구를 강제할수 있다
    		//원하는 상황에서 따로 사용이 가능하다
    		super(message);
    	}
    }
    ```

* throw - 원하는 상황에서 예외를 만들수 있다

```
package class02;

import java.util.InputMismatchException;
import java.util.Scanner;

class MyException extends Exception {//내가 원하는 예외 생성
	MyException(String message) {
		//특정문구를 강제할수 있다
		//원하는 상황에서 따로 사용이 가능하다
		super(message);
	}
}

public class Test01 {
	public static void main(String[] args) {
		int num = 10;
		int x;
		Scanner sc = new Scanner(System.in);
		MyException myExcep = new MyException("0~100까지만 입력 가능");

		while (true) {
			System.out.print("입력 : ");
			try {
				x = sc.nextInt();
				if (x < 0 || x > 100) {
					throw myExcep;// 예외를 발생시키는 친구, try가 무조건 필요하다
				}
				System.out.println(num / x);
			} catch (ArithmeticException e) {//수학적 오류(0으로 나눌순 없다)
				System.out.println("0으로는 나눌수 없습니다");
			} catch (InputMismatchException e) {//int가 아닌 다른 타입을 쓸경우
				System.out.println("정수만 입력하세요");
				//sc = new Scanner(System.in);
				sc.nextLine();
			} catch (MyException e) {//원하는 상황에서 
				System.out.println(e.getMessage());
			} catch (Exception e) {// 최상위 예외 클래스, 예외중 마지막에 써야한다
				System.out.println("예외 발생");
				e.printStackTrace();//예외의 상세 내용을 보여줌
				//	1 - 어떤 타입의 예외인지(클래스)
				//	2 - 상세설명
				//	3 - 발생한 라인
			}finally {//무조건 실행
				System.out.println("프로그램을 이용해주셔서 감사합니다");
			}
		}
	}
}
```

* 예외 미루기
  * 예외처리를 떠넘기는게 가능하다

```
package class02;

public class Test03 {//예외처리 미루기
	
	static void f1() throws Exception{
		int a = 10;
		int b = 0;
		System.out.println(a/b);
	}
	static void f2() throws Exception{
		Exception excep = new Exception("예외");
		throw excep;
	}
	
	public static void main(String[] args) {
		//static = 객체와 무관하게
		// 1 클래스 변수(공유 자원)
		// 2 클래스 외부에서 함수 단독선언
		
		try {
			f1();
			f2();//그냥은 못쓴다
		} catch (Exception e) {
			// TODO Auto-generated catch block
			System.out.println("예외 넘기기");
		}
	}
}
```

